import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1", title: "HC Verma Physics Vol 1 & 2",
    description: "Both volumes in excellent condition. Lightly annotated with pencil, easily erasable. Perfect for JEE prep.",
    price: 150, images: ["https://picsum.photos/seed/book1/400/300"],
    category: "Books", hostel: "KP-5", condition: "like_new", negotiable: true,
    seller: { id: "s1", name: "Arjun Mehta", hostel: "KP-5" },
    createdAt: "2024-11-01T10:00:00Z", sold: false, views: 124,
  },
  {
    id: "2", title: "Casio fx-991EX Scientific Calculator",
    description: "Top-of-the-line scientific calculator. Works perfectly. Includes original case and manual.",
    price: 800, images: ["https://picsum.photos/seed/calc1/400/300"],
    category: "Electronics", hostel: "KP-3", condition: "good", negotiable: false,
    seller: { id: "s2", name: "Rohan Das", hostel: "KP-3" },
    createdAt: "2024-11-03T09:30:00Z", sold: false, views: 230,
  },
  {
    id: "3", title: "Dell 65W Laptop Charger (Type-C)",
    description: "Original Dell charger, compatible with most Dell Inspiron/Latitude laptops. 2 months old.",
    price: 500, images: ["https://picsum.photos/seed/charger1/400/300"],
    category: "Electronics", hostel: "QC-4", condition: "like_new", negotiable: true,
    seller: { id: "s3", name: "Priya Sharma", hostel: "QC-4" },
    createdAt: "2024-11-05T14:00:00Z", sold: false, views: 89,
  },
  {
    id: "4", title: "LED Study Table Lamp (Adjustable)",
    description: "Bright, eye-friendly LED desk lamp with 3 brightness modes and USB charging port. Barely used.",
    price: 300, images: ["https://picsum.photos/seed/lamp1/400/300"],
    category: "Electronics", hostel: "KP-8", condition: "good", negotiable: true,
    seller: { id: "s4", name: "Siddharth Nair", hostel: "KP-8" },
    createdAt: "2024-11-07T11:00:00Z", sold: false, views: 67,
  },
  {
    id: "5", title: "SG Cricket Bat (Full Size)",
    description: "SG English willow bat, Grade 2. Light pick-up. Few minor dents but great for practice matches.",
    price: 1200, images: ["https://picsum.photos/seed/bat1/400/300"],
    category: "Sports", hostel: "KP-12", condition: "good", negotiable: true,
    seller: { id: "s5", name: "Vikram Singh", hostel: "KP-12" },
    createdAt: "2024-11-08T16:30:00Z", sold: false, views: 55,
  },
  {
    id: "6", title: "Formal White Shirt (Size M)",
    description: "Raymond formal shirt, worn only twice for campus events. Dry-cleaned and ready to wear.",
    price: 400, images: ["https://picsum.photos/seed/shirt1/400/300"],
    category: "Clothes", hostel: "QC-7", condition: "like_new", negotiable: false,
    seller: { id: "s6", name: "Ananya Roy", hostel: "QC-7" },
    createdAt: "2024-11-09T08:00:00Z", sold: false, views: 43,
  },
  {
    id: "7", title: "Electric Kettle 1.5L (Prestige)",
    description: "Prestige electric kettle, auto-cutoff feature. Perfect for instant noodles and tea. Minor limescale.",
    price: 600, images: ["https://picsum.photos/seed/kettle1/400/300"],
    category: "Appliances", hostel: "KP-2", condition: "good", negotiable: true,
    seller: { id: "s7", name: "Aman Gupta", hostel: "KP-2" },
    createdAt: "2024-11-10T13:00:00Z", sold: false, views: 198,
  },
  {
    id: "8", title: "Yoga Mat with Carry Strap",
    description: "6mm thick TPE yoga mat. Non-slip surface, odour-free. Used for 3 months. Good condition.",
    price: 250, images: ["https://picsum.photos/seed/yoga1/400/300"],
    category: "Sports", hostel: "QC-9", condition: "like_new", negotiable: false,
    seller: { id: "s8", name: "Kavita Pillai", hostel: "QC-9" },
    createdAt: "2024-11-11T09:00:00Z", sold: false, views: 72,
  },
  {
    id: "9", title: "Sony WH-1000XM4 Earbuds",
    description: "Sony true wireless earbuds, excellent noise cancellation. Both earbuds and case working fine.",
    price: 2200, images: ["https://picsum.photos/seed/earphone1/400/300"],
    category: "Electronics", hostel: "KP-15", condition: "good", negotiable: true,
    seller: { id: "s9", name: "Harsh Patel", hostel: "KP-15" },
    createdAt: "2024-11-12T17:00:00Z", sold: false, views: 312,
  },
  {
    id: "10", title: "JEE Advanced 2019-2023 Papers Bundle",
    description: "5 years of JEE Advanced papers with solutions. Printed and spiral-bound. Clean copy.",
    price: 80, images: ["https://picsum.photos/seed/papers1/400/300"],
    category: "Books", hostel: "KP-4", condition: "good", negotiable: false,
    seller: { id: "s10", name: "Tanvi Joshi", hostel: "KP-4" },
    createdAt: "2024-11-13T10:30:00Z", sold: false, views: 156,
  },
  {
    id: "11", title: "Mechanical Keyboard (Red Switches)",
    description: "HyperX Alloy mechanical keyboard. RGB backlighting. All keys working. Bought 6 months ago.",
    price: 1800, images: ["https://picsum.photos/seed/keyboard1/400/300"],
    category: "Electronics", hostel: "KP-7", condition: "like_new", negotiable: false,
    seller: { id: "s11", name: "Dev Kapoor", hostel: "KP-7" },
    createdAt: "2024-11-14T12:00:00Z", sold: false, views: 267,
  },
  {
    id: "12", title: "Dumbbell Set 5kg Pair (Hex)",
    description: "Rubber hex dumbbells, 5kg each (10kg total). No chips or cracks. Great for room workouts.",
    price: 750, images: ["https://picsum.photos/seed/dumbbells1/400/300"],
    category: "Sports", hostel: "KP-20", condition: "good", negotiable: true,
    seller: { id: "s12", name: "Rahul Verma", hostel: "KP-20" },
    createdAt: "2024-11-15T08:30:00Z", sold: false, views: 88,
  },
  {
    id: "13", title: "Business Casual Blazer (Size 40)",
    description: "Navy blue blazer, fits size 40. Worn at placement events. Dry-cleaned and stored carefully.",
    price: 900, images: ["https://picsum.photos/seed/blazer1/400/300"],
    category: "Clothes", hostel: "QC-2", condition: "like_new", negotiable: false,
    seller: { id: "s13", name: "Ishita Bose", hostel: "QC-2" },
    createdAt: "2024-11-16T15:00:00Z", sold: false, views: 61,
  },
  {
    id: "14", title: "USB Mini Table Fan",
    description: "Compact USB-powered desk fan. 3 speed settings. Super quiet. Great during power cuts.",
    price: 200, images: ["https://picsum.photos/seed/fan1/400/300"],
    category: "Appliances", hostel: "QC-11", condition: "good", negotiable: true,
    seller: { id: "s14", name: "Meera Sundaram", hostel: "QC-11" },
    createdAt: "2024-11-17T11:00:00Z", sold: false, views: 43,
  },
  {
    id: "15", title: "Wacom Intuos Small Drawing Tablet",
    description: "Wacom Intuos CTL-4100 with stylus and extra nibs. Works on Win/Mac. Driver CD included.",
    price: 2500, images: ["https://picsum.photos/seed/wacom1/400/300"],
    category: "Electronics", hostel: "QC-6", condition: "good", negotiable: true,
    seller: { id: "s15", name: "Sneha Rao", hostel: "QC-6" },
    createdAt: "2024-11-18T14:30:00Z", sold: false, views: 189,
  },
  {
    id: "16", title: "Organic Chemistry by Morrison Boyd",
    description: "Classic organic chemistry textbook. Some highlighting in first 5 chapters, rest clean.",
    price: 200, images: ["https://picsum.photos/seed/chem1/400/300"],
    category: "Books", hostel: "KP-9", condition: "fair", negotiable: true,
    seller: { id: "s16", name: "Karan Malhotra", hostel: "KP-9" },
    createdAt: "2024-11-19T09:00:00Z", sold: false, views: 102,
  },
  {
    id: "17", title: "Men's Formal Leather Shoes (Size 9)",
    description: "Black leather formal shoes, worn 4-5 times. Cleaned and polished. Original box included.",
    price: 600, images: ["https://picsum.photos/seed/shoes1/400/300"],
    category: "Clothes", hostel: "KP-18", condition: "like_new", negotiable: false,
    seller: { id: "s17", name: "Nikhil Tiwari", hostel: "KP-18" },
    createdAt: "2024-11-20T10:00:00Z", sold: false, views: 77,
  },
  {
    id: "18", title: "Football (Cosco Size 5)",
    description: "Cosco Argentina football, size 5. Good grip. Minor scuff marks on surface. Pumped and ready.",
    price: 350, images: ["https://picsum.photos/seed/football1/400/300"],
    category: "Sports", hostel: "KP-13", condition: "good", negotiable: true,
    seller: { id: "s18", name: "Aditya Kumar", hostel: "KP-13" },
    createdAt: "2024-11-21T16:00:00Z", sold: false, views: 49,
  },
  {
    id: "19", title: "Extension Cord 4-Plug (5m)",
    description: "Anchor 4-plug extension cord with surge protection. 5-metre wire. ISI marked. Works perfectly.",
    price: 250, images: ["https://picsum.photos/seed/ext1/400/300"],
    category: "Accessories", hostel: "KP-1", condition: "good", negotiable: false,
    seller: { id: "s19", name: "Saurav Banerjee", hostel: "KP-1" },
    createdAt: "2024-11-22T08:00:00Z", sold: false, views: 134,
  },
  {
    id: "20", title: "Milton Steel Water Bottle 1L",
    description: "Insulated steel bottle, keeps water cold 18 hrs. Minor dent on bottom, functional. Leak-proof.",
    price: 180, images: ["https://picsum.photos/seed/bottle1/400/300"],
    category: "Accessories", hostel: "KP-1", condition: "good", negotiable: false,
    seller: { id: "s20", name: "Saurav Banerjee", hostel: "KP-1" },
    createdAt: "2024-11-23T10:00:00Z", sold: false, views: 38,
  },
  // recently sold items
  {
    id: "21", title: "Noise Cancelling Headphones",
    description: "Sold already.", price: 1500,
    images: ["https://picsum.photos/seed/head1/400/300"],
    category: "Electronics", hostel: "KP-11", condition: "good", negotiable: false,
    seller: { id: "s21", name: "Pooja Iyer", hostel: "KP-11" },
    createdAt: "2024-10-20T10:00:00Z", sold: true, views: 345,
  },
  {
    id: "22", title: "Physics Galaxy by Ashish Arora",
    description: "Sold.", price: 350,
    images: ["https://picsum.photos/seed/book2/400/300"],
    category: "Books", hostel: "KP-6", condition: "good", negotiable: false,
    seller: { id: "s22", name: "Gaurav Sen", hostel: "KP-6" },
    createdAt: "2024-10-22T10:00:00Z", sold: true, views: 201,
  },
  {
    id: "23", title: "USB-C Hub 7-in-1",
    description: "Sold.", price: 900,
    images: ["https://picsum.photos/seed/hub1/400/300"],
    category: "Electronics", hostel: "QC-3", condition: "like_new", negotiable: false,
    seller: { id: "s23", name: "Divya Nambiar", hostel: "QC-3" },
    createdAt: "2024-10-25T10:00:00Z", sold: true, views: 178,
  },
  {
    id: "24", title: "Badminton Racket Set (2 pcs)",
    description: "Sold.", price: 450,
    images: ["https://picsum.photos/seed/badminton1/400/300"],
    category: "Sports", hostel: "KP-16", condition: "good", negotiable: false,
    seller: { id: "s24", name: "Rohit Yadav", hostel: "KP-16" },
    createdAt: "2024-10-28T10:00:00Z", sold: true, views: 93,
  },
];
