import type { Poll, PollReply } from "@/types/poll";

export const MOCK_POLLS: Poll[] = [
  {
    id: "poll1",
    itemName: "Organic Chemistry Textbook",
    description: "Looking for Organic Chemistry by Morrison Boyd or similar. Needed urgently for 3rd sem exams. Please DM if you have one.",
    category: "Books",
    maxPrice: 200,
    hostelId: "KP-7",
    buyerId: "buyer456",
    buyerName: "Aryan Kapoor",
    buyerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Aryan+Kapoor&backgroundColor=7C3AED",
    status: "open",
    createdAt: "2026-05-25T10:00:00Z",
    replyCount: 2,
  },
  {
    id: "poll2",
    itemName: "Study Table Lamp",
    description: "Need a good LED desk lamp, preferably with warm and cool light modes. Budget is flexible.",
    category: "Electronics",
    maxPrice: 500,
    hostelId: "QC-3",
    buyerId: "buyer123",
    buyerName: "Campus Buyer",
    buyerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Campus+Buyer&backgroundColor=7C3AED",
    status: "open",
    createdAt: "2026-05-24T14:30:00Z",
    replyCount: 1,
  },
  {
    id: "poll3",
    itemName: "Badminton Racket",
    description: "Looking for a decent badminton racket and shuttle. Can buy as a set or individually.",
    category: "Sports",
    maxPrice: 400,
    hostelId: "KP-12",
    buyerId: "buyer789",
    buyerName: "Nikhil Bose",
    buyerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Nikhil+Bose&backgroundColor=0ea5e9",
    status: "open",
    createdAt: "2026-05-23T09:00:00Z",
    replyCount: 0,
  },
  {
    id: "poll4",
    itemName: "Casio Scientific Calculator",
    description: "Need FX-991EX for engineering maths. Anyone selling?",
    category: "Electronics",
    maxPrice: 700,
    hostelId: "KP-3",
    buyerId: "buyer321",
    buyerName: "Sneha Patel",
    buyerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Sneha+Patel&backgroundColor=ec4899",
    status: "closed",
    createdAt: "2026-05-20T11:00:00Z",
    replyCount: 3,
  },
  {
    id: "poll5",
    itemName: "Ethernet Cable 5m",
    description: "Need a CAT6 ethernet cable, around 5 metres length for wired internet in room.",
    category: "Electronics",
    maxPrice: 150,
    hostelId: "QC-8",
    buyerId: "buyer654",
    buyerName: "Divya Rao",
    buyerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Divya+Rao&backgroundColor=10b981",
    status: "open",
    createdAt: "2026-05-26T08:00:00Z",
    replyCount: 0,
  },
];

export const MOCK_POLL_REPLIES: Record<string, PollReply[]> = {
  poll1: [
    {
      id: "r1", pollId: "poll1", sellerId: "s1", sellerName: "Priya Sharma",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Priya+Sharma&backgroundColor=ec4899",
      message: "I have Morrison Boyd, used for one semester. In good condition!", price: 180,
      createdAt: "2026-05-25T11:00:00Z",
    },
    {
      id: "r2", pollId: "poll1", sellerId: "s5", sellerName: "Karan Singh",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Karan+Singh&backgroundColor=7C3AED",
      message: "I have a copy with some highlights but all pages intact. Can give for ₹150.", price: 150,
      createdAt: "2026-05-25T13:00:00Z",
    },
  ],
  poll2: [
    {
      id: "r3", pollId: "poll2", sellerId: "s3", sellerName: "Anjali Mehta",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Anjali+Mehta&backgroundColor=10b981",
      message: "Have a Syska LED lamp, dual colour mode. Barely used, selling for ₹400.", price: 400,
      createdAt: "2026-05-24T16:00:00Z",
    },
  ],
  poll4: [
    {
      id: "r4", pollId: "poll4", sellerId: "s2", sellerName: "Rahul Verma",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Rahul+Verma&backgroundColor=0ea5e9",
      message: "Have the exact model FX-991EX, ₹650.", price: 650,
      createdAt: "2026-05-20T12:00:00Z",
    },
    {
      id: "r5", pollId: "poll4", sellerId: "s6", sellerName: "Meera Joshi",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Meera+Joshi&backgroundColor=f59e0b",
      message: "I have FX-82EX, slightly older model. ₹350 if that works?", price: 350,
      createdAt: "2026-05-20T14:00:00Z",
    },
    {
      id: "r6", pollId: "poll4", sellerId: "s7", sellerName: "Amit Kumar",
      sellerAvatar: "https://api.dicebear.com/7.x/initials/svg?seed=Amit+Kumar&backgroundColor=8b5cf6",
      message: "FX-991EX available, ₹600. Can meet at KP common room.", price: 600,
      createdAt: "2026-05-21T09:00:00Z",
    },
  ],
};
